apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic-deployment  
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: pet-clinic-web
  template:
    metadata:
      labels:
        component: pet-clinic-web
    spec:
      containers:
        - name: pet-clinic-web
          image: bobjwalker99/octopetshop-web:0.0.1          
          imagePullPolicy: "Always"
          ports:
           - containerPort: 5000
             name: http-port
          env:
            - name: ProductServiceBaseUrl
              value: http://octopetshop-productservice-cluster-ip-service:5011/
            - name: ShoppingCartServiceBaseUrl
              value: http://octopetshop-shoppingcart-cluster-ip-service:5012          
---
apiVersion: v1
kind: Service
metadata:
  name: pet-clinic-web-cluster-ip-service  
spec:
  type: ClusterIP
  selector:
    component: pet-clinic-web
  ports:
    - port: 6800
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: randomquotes-ingress-nginx  
spec:
  ingressClassName: nginx
  rules:
    - host: petclinic.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pet-clinic-web-cluster-ip-service
                port:
                  number: 6800